// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2STaskMsg.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Game.Protobuf.C2S {

  /// <summary>Holder for reflection information generated from C2STaskMsg.proto</summary>
  public static partial class C2STaskMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for C2STaskMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static C2STaskMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDMlNUYXNrTXNnLnByb3RvEhVvcmcuZ2FtZS5wcm90b2J1Zi5jMnMiQwoQ",
            "QzJTR2V0QWxsVGFza01zZyIvCgVNc2dJRBIZChVFTlVOX1RZUEVfVU5TUEVD",
            "SUZJRUQQABILCgZlTXNnSUQQzQhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Game.Protobuf.C2S.C2SGetAllTaskMsg), global::Org.Game.Protobuf.C2S.C2SGetAllTaskMsg.Parser, null, null, new[]{ typeof(global::Org.Game.Protobuf.C2S.C2SGetAllTaskMsg.Types.MsgID) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  获取全部任务
  ///  code = 1101
  /// </summary>
  public sealed partial class C2SGetAllTaskMsg : pb::IMessage<C2SGetAllTaskMsg> {
    private static readonly pb::MessageParser<C2SGetAllTaskMsg> _parser = new pb::MessageParser<C2SGetAllTaskMsg>(() => new C2SGetAllTaskMsg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2SGetAllTaskMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Game.Protobuf.C2S.C2STaskMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2SGetAllTaskMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2SGetAllTaskMsg(C2SGetAllTaskMsg other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2SGetAllTaskMsg Clone() {
      return new C2SGetAllTaskMsg(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as C2SGetAllTaskMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(C2SGetAllTaskMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(C2SGetAllTaskMsg other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the C2SGetAllTaskMsg message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MsgID {
        [pbr::OriginalName("ENUN_TYPE_UNSPECIFIED")] EnunTypeUnspecified = 0,
        [pbr::OriginalName("eMsgID")] EMsgId = 1101,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
